// <auto-generated />
namespace AppAdvogados.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Certo07_11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Certo07_11));
        
        string IMigrationMetadata.Id
        {
            get { return "201711072255357_Certo07_11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
